# coding: utf-8

"""
    MTConnect – REST API

    MTConnect REST API   # noqa: E501

    OpenAPI spec version: MTConnect Agent Version 2.4.0.7
    Contact: will@metalogi.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cppagent
from cppagent.api.default_api import DefaultApi  # noqa: E501
from cppagent.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_asset_asset_id_delete(self):
        """Test case for asset_asset_id_delete

        Delete asset identified by `assetId`  # noqa: E501
        """
        pass

    def test_asset_asset_id_post(self):
        """Test case for asset_asset_id_post

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_asset_asset_id_put(self):
        """Test case for asset_asset_id_put

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_asset_asset_ids_get(self):
        """Test case for asset_asset_ids_get

        MTConnect asset request  # noqa: E501
        """
        pass

    def test_asset_delete(self):
        """Test case for asset_delete

        Delete all assets for a device and type  # noqa: E501
        """
        pass

    def test_asset_get(self):
        """Test case for asset_get

        MTConnect asset request  # noqa: E501
        """
        pass

    def test_asset_post(self):
        """Test case for asset_post

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_asset_put(self):
        """Test case for asset_put

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_assets_asset_id_delete(self):
        """Test case for assets_asset_id_delete

        Delete asset identified by `assetId`  # noqa: E501
        """
        pass

    def test_assets_asset_id_post(self):
        """Test case for assets_asset_id_post

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_assets_asset_id_put(self):
        """Test case for assets_asset_id_put

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_assets_asset_ids_get(self):
        """Test case for assets_asset_ids_get

        MTConnect assets request  # noqa: E501
        """
        pass

    def test_assets_delete(self):
        """Test case for assets_delete

        Delete all assets for a device and type  # noqa: E501
        """
        pass

    def test_assets_get(self):
        """Test case for assets_get

        MTConnect assets request  # noqa: E501
        """
        pass

    def test_assets_post(self):
        """Test case for assets_post

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_assets_put(self):
        """Test case for assets_put

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_current_get(self):
        """Test case for current_get

        MTConnect current request  # noqa: E501
        """
        pass

    def test_device_asset_asset_id_post(self):
        """Test case for device_asset_asset_id_post

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_device_asset_asset_id_put(self):
        """Test case for device_asset_asset_id_put

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_device_asset_delete(self):
        """Test case for device_asset_delete

        Delete all assets for a device and type  # noqa: E501
        """
        pass

    def test_device_asset_get(self):
        """Test case for device_asset_get

        MTConnect asset request  # noqa: E501
        """
        pass

    def test_device_asset_post(self):
        """Test case for device_asset_post

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_device_asset_put(self):
        """Test case for device_asset_put

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_device_assets_asset_id_post(self):
        """Test case for device_assets_asset_id_post

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_device_assets_asset_id_put(self):
        """Test case for device_assets_asset_id_put

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_device_assets_delete(self):
        """Test case for device_assets_delete

        Delete all assets for a device and type  # noqa: E501
        """
        pass

    def test_device_assets_get(self):
        """Test case for device_assets_get

        MTConnect assets request  # noqa: E501
        """
        pass

    def test_device_assets_post(self):
        """Test case for device_assets_post

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_device_assets_put(self):
        """Test case for device_assets_put

        Upload an asset by identified by `assetId`  # noqa: E501
        """
        pass

    def test_device_current_get(self):
        """Test case for device_current_get

        MTConnect current request  # noqa: E501
        """
        pass

    def test_device_get(self):
        """Test case for device_get

        MTConnect probe request  # noqa: E501
        """
        pass

    def test_device_post(self):
        """Test case for device_post

        Non-normative POST to update a value in the agent  # noqa: E501
        """
        pass

    def test_device_probe_get(self):
        """Test case for device_probe_get

        MTConnect probe request  # noqa: E501
        """
        pass

    def test_device_put(self):
        """Test case for device_put

        Non-normative PUT to update a value in the agent  # noqa: E501
        """
        pass

    def test_device_sample_get(self):
        """Test case for device_sample_get

        MTConnect sample request  # noqa: E501
        """
        pass

    def test_probe_get(self):
        """Test case for probe_get

        MTConnect probe request  # noqa: E501
        """
        pass

    def test_root_get(self):
        """Test case for root_get

        MTConnect probe request  # noqa: E501
        """
        pass

    def test_sample_get(self):
        """Test case for sample_get

        MTConnect sample request  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
