# coding: utf-8

"""
    MTConnect – REST API

    MTConnect REST API   # noqa: E501

    OpenAPI spec version: MTConnect Agent Version 2.4.0.8
    Contact: will@metalogi.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mtconnect
from mtconnect.models.inline_response200 import InlineResponse200  # noqa: E501
from mtconnect.rest import ApiException


class TestInlineResponse200(unittest.TestCase):
    """InlineResponse200 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200(self):
        """Test InlineResponse200"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mtconnect.models.inline_response200.InlineResponse200()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
