version: '3.8'

services:
  swagger-codegen:
    image: swaggerapi/swagger-codegen-cli-v3
    volumes:
      - /home/robot-ranger/development/process-robotics/workspace/cppagent-rest-client:/local
    # command: ls -la
    command: generate -i /local/swagger.json -l python -o /local -DpackageName=mtconnect