# coding: utf-8

"""
    MTConnect – REST API

    MTConnect REST API   # noqa: E501

    OpenAPI spec version: MTConnect Agent Version 2.4.0.7
    Contact: will@metalogi.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "mtconnect"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="MTConnect – REST API",
    author_email="will@metalogi.io",
    url="",
    keywords=["Swagger", "MTConnect – REST API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    MTConnect REST API   # noqa: E501
    """
)
